## our React TodoMVC app is written
## in node so thats what we select.
## Cypress is agnostic to your apps
## backend language though.
language: node_js

node_js:
  - 6

cache:
  directories:
    - ~/.npm
    - node_modules

install:
  - npm install

before_script:
  - npm run ci:start -- &

script:
  - npm run ci:test
